// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwe8kQoYF7NrpPkJ52MIse3VvqhWcXnHE',
    appId: '1:621805123016:web:1e3dd66f2ec51116617cfd',
    messagingSenderId: '621805123016',
    projectId: 'barberappointment-25924',
    authDomain: 'barberappointment-25924.firebaseapp.com',
    storageBucket: 'barberappointment-25924.firebasestorage.app',
    measurementId: 'G-DJCHCLR36V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRQHyW-UTB0HwTaTvA03Dj3Ij01eS0BW4',
    appId: '1:621805123016:android:245e52eef719c1d2617cfd',
    messagingSenderId: '621805123016',
    projectId: 'barberappointment-25924',
    storageBucket: 'barberappointment-25924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ0OwfiiebeM4s8ergRx-PewGIx9LUyBo',
    appId: '1:621805123016:ios:c9cf4d4701366f5d617cfd',
    messagingSenderId: '621805123016',
    projectId: 'barberappointment-25924',
    storageBucket: 'barberappointment-25924.firebasestorage.app',
    iosBundleId: 'com.example.barberappointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ0OwfiiebeM4s8ergRx-PewGIx9LUyBo',
    appId: '1:621805123016:ios:c9cf4d4701366f5d617cfd',
    messagingSenderId: '621805123016',
    projectId: 'barberappointment-25924',
    storageBucket: 'barberappointment-25924.firebasestorage.app',
    iosBundleId: 'com.example.barberappointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwe8kQoYF7NrpPkJ52MIse3VvqhWcXnHE',
    appId: '1:621805123016:web:b7db47643d8521d1617cfd',
    messagingSenderId: '621805123016',
    projectId: 'barberappointment-25924',
    authDomain: 'barberappointment-25924.firebaseapp.com',
    storageBucket: 'barberappointment-25924.firebasestorage.app',
    measurementId: 'G-JQ92X9JY0Z',
  );
}
